-- -------------------------------------------------------------
-- 
-- File Name: tmp_vhdl\cam_encoder_fpga_module\sg_came_Cam_Encoder_FPGA_Code_Module.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Camshaft                      ce_out        0.2
-- Version                       ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sg_came_Cam_Encoder_FPGA_Code_Module
-- Source Path: cam_encoder_fpga_module/Cam Encoder FPGA Code Module
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sg_came_Cam_Encoder_FPGA_Code_Module IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Angle                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Direction                         :   IN    std_logic;
        Cam_On_0                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_1                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_2                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_3                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_4                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_5                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_6                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_7                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_8                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_On_9                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_3                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_4                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_5                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_6                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_7                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_8                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Cam_Off_9                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Enable                            :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Camshaft                          :   OUT   std_logic;
        Version                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END sg_came_Cam_Encoder_FPGA_Code_Module;


ARCHITECTURE rtl OF sg_came_Cam_Encoder_FPGA_Code_Module IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Direction_1                      : std_logic;
  SIGNAL FixPt_Relational_Operator_relop1 : std_logic;
  SIGNAL Enable_1                         : std_logic;
  SIGNAL FixPt_Relational_Operator1_relop1 : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Bitwise_Operator3_out1           : std_logic;
  SIGNAL Cam_Off_0_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Cam_On_0_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Angle_unsigned                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL Relational_Operator1_relop1      : std_logic;
  SIGNAL Bitwise_Operator_out1            : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1           : std_logic;
  SIGNAL Relational_Operator2_relop1      : std_logic;
  SIGNAL switch_compare_1_2               : std_logic;
  SIGNAL Switch_out1                      : std_logic;
  SIGNAL FixPt_Relational_Operator2_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1           : std_logic;
  SIGNAL FixPt_Relational_Operator3_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1           : std_logic;
  SIGNAL Bitwise_Operator1_out1_1         : std_logic;
  SIGNAL Latch_Off_Active_out1            : std_logic;
  SIGNAL Switch2_out1                     : std_logic;
  SIGNAL Bitwise_Operator1_out1_2         : std_logic;
  SIGNAL switch_compare_1_3               : std_logic;
  SIGNAL Switch_out1_1                    : std_logic;
  SIGNAL Compare_To_Zero1_out1            : std_logic;
  SIGNAL Bitwise_Operator7_out1           : std_logic;
  SIGNAL Bitwise_Operator6_out1           : std_logic;
  SIGNAL Bitwise_Operator5_out1           : std_logic;
  SIGNAL Latch_On_Active_out1             : std_logic;
  SIGNAL Switch3_out1                     : std_logic;
  SIGNAL switch_compare_1_4               : std_logic;
  SIGNAL Switch1_out1                     : std_logic;
  SIGNAL Bitwise_Operator8_out1           : std_logic;
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL Bitwise_Operator_out1_1          : std_logic;
  SIGNAL Switch1_out1_1                   : std_logic;
  SIGNAL Comparators_out1                 : std_logic;
  SIGNAL Bitwise_Operator_out1_2          : std_logic;
  SIGNAL Relational_Operator3_relop1      : std_logic;
  SIGNAL switch_compare_1_5               : std_logic;
  SIGNAL FixPt_Relational_Operator4_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator5_relop1 : std_logic;
  SIGNAL switch_compare_1_6               : std_logic;
  SIGNAL Bitwise_Operator3_out1_1         : std_logic;
  SIGNAL Cam_Off_1_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_7               : std_logic;
  SIGNAL Cam_On_1_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator4_relop1      : std_logic;
  SIGNAL Relational_Operator11_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_3          : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_1 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_3         : std_logic;
  SIGNAL Relational_Operator21_relop1     : std_logic;
  SIGNAL switch_compare_1_8               : std_logic;
  SIGNAL Switch_out1_2                    : std_logic;
  SIGNAL FixPt_Relational_Operator6_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_1         : std_logic;
  SIGNAL FixPt_Relational_Operator7_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_1         : std_logic;
  SIGNAL Bitwise_Operator1_out1_4         : std_logic;
  SIGNAL Latch_Off_Active_out1_1          : std_logic;
  SIGNAL Switch2_out1_1                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_5         : std_logic;
  SIGNAL switch_compare_1_9               : std_logic;
  SIGNAL Switch_out1_3                    : std_logic;
  SIGNAL Compare_To_Zero1_out1_1          : std_logic;
  SIGNAL Bitwise_Operator7_out1_1         : std_logic;
  SIGNAL Bitwise_Operator6_out1_1         : std_logic;
  SIGNAL Bitwise_Operator5_out1_1         : std_logic;
  SIGNAL Latch_On_Active_out1_1           : std_logic;
  SIGNAL Switch3_out1_1                   : std_logic;
  SIGNAL switch_compare_1_10              : std_logic;
  SIGNAL Switch1_out1_2                   : std_logic;
  SIGNAL Bitwise_Operator8_out1_1         : std_logic;
  SIGNAL Compare_To_Zero_out1_1           : std_logic;
  SIGNAL Bitwise_Operator_out1_4          : std_logic;
  SIGNAL Switch1_out1_3                   : std_logic;
  SIGNAL Comparators_out1_1               : std_logic;
  SIGNAL Bitwise_Operator_out1_5          : std_logic;
  SIGNAL Relational_Operator31_relop1     : std_logic;
  SIGNAL switch_compare_1_11              : std_logic;
  SIGNAL FixPt_Relational_Operator8_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator9_relop1 : std_logic;
  SIGNAL switch_compare_1_12              : std_logic;
  SIGNAL Bitwise_Operator3_out1_2         : std_logic;
  SIGNAL Cam_Off_2_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_13              : std_logic;
  SIGNAL Cam_On_2_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator5_relop1      : std_logic;
  SIGNAL Relational_Operator12_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_6          : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_2 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_2 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_6         : std_logic;
  SIGNAL Relational_Operator22_relop1     : std_logic;
  SIGNAL switch_compare_1_14              : std_logic;
  SIGNAL Switch_out1_4                    : std_logic;
  SIGNAL FixPt_Relational_Operator10_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_2         : std_logic;
  SIGNAL FixPt_Relational_Operator11_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_2         : std_logic;
  SIGNAL Bitwise_Operator1_out1_7         : std_logic;
  SIGNAL Latch_Off_Active_out1_2          : std_logic;
  SIGNAL Switch2_out1_2                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_8         : std_logic;
  SIGNAL switch_compare_1_15              : std_logic;
  SIGNAL Switch_out1_5                    : std_logic;
  SIGNAL Compare_To_Zero1_out1_2          : std_logic;
  SIGNAL Bitwise_Operator7_out1_2         : std_logic;
  SIGNAL Bitwise_Operator6_out1_2         : std_logic;
  SIGNAL Bitwise_Operator5_out1_2         : std_logic;
  SIGNAL Latch_On_Active_out1_2           : std_logic;
  SIGNAL Switch3_out1_2                   : std_logic;
  SIGNAL switch_compare_1_16              : std_logic;
  SIGNAL Switch1_out1_4                   : std_logic;
  SIGNAL Bitwise_Operator8_out1_2         : std_logic;
  SIGNAL Compare_To_Zero_out1_2           : std_logic;
  SIGNAL Bitwise_Operator_out1_7          : std_logic;
  SIGNAL Switch1_out1_5                   : std_logic;
  SIGNAL Comparators_out1_2               : std_logic;
  SIGNAL Bitwise_Operator_out1_8          : std_logic;
  SIGNAL Relational_Operator32_relop1     : std_logic;
  SIGNAL switch_compare_1_17              : std_logic;
  SIGNAL FixPt_Relational_Operator12_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator13_relop1 : std_logic;
  SIGNAL switch_compare_1_18              : std_logic;
  SIGNAL Bitwise_Operator3_out1_3         : std_logic;
  SIGNAL Cam_Off_3_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_19              : std_logic;
  SIGNAL Cam_On_3_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator6_relop1      : std_logic;
  SIGNAL Relational_Operator13_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_9          : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_3 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_3 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_9         : std_logic;
  SIGNAL Relational_Operator23_relop1     : std_logic;
  SIGNAL switch_compare_1_20              : std_logic;
  SIGNAL Switch_out1_6                    : std_logic;
  SIGNAL FixPt_Relational_Operator14_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_3         : std_logic;
  SIGNAL FixPt_Relational_Operator15_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_3         : std_logic;
  SIGNAL Bitwise_Operator1_out1_10        : std_logic;
  SIGNAL Latch_Off_Active_out1_3          : std_logic;
  SIGNAL Switch2_out1_3                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_11        : std_logic;
  SIGNAL switch_compare_1_21              : std_logic;
  SIGNAL Switch_out1_7                    : std_logic;
  SIGNAL Compare_To_Zero1_out1_3          : std_logic;
  SIGNAL Bitwise_Operator7_out1_3         : std_logic;
  SIGNAL Bitwise_Operator6_out1_3         : std_logic;
  SIGNAL Bitwise_Operator5_out1_3         : std_logic;
  SIGNAL Latch_On_Active_out1_3           : std_logic;
  SIGNAL Switch3_out1_3                   : std_logic;
  SIGNAL switch_compare_1_22              : std_logic;
  SIGNAL Switch1_out1_6                   : std_logic;
  SIGNAL Bitwise_Operator8_out1_3         : std_logic;
  SIGNAL Compare_To_Zero_out1_3           : std_logic;
  SIGNAL Bitwise_Operator_out1_10         : std_logic;
  SIGNAL Switch1_out1_7                   : std_logic;
  SIGNAL Comparators_out1_3               : std_logic;
  SIGNAL Bitwise_Operator_out1_11         : std_logic;
  SIGNAL Relational_Operator33_relop1     : std_logic;
  SIGNAL switch_compare_1_23              : std_logic;
  SIGNAL FixPt_Relational_Operator16_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator17_relop1 : std_logic;
  SIGNAL switch_compare_1_24              : std_logic;
  SIGNAL Bitwise_Operator3_out1_4         : std_logic;
  SIGNAL Cam_Off_4_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_25              : std_logic;
  SIGNAL Cam_On_4_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator7_relop1      : std_logic;
  SIGNAL Relational_Operator14_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_12         : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_4 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_4 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_12        : std_logic;
  SIGNAL Relational_Operator24_relop1     : std_logic;
  SIGNAL switch_compare_1_26              : std_logic;
  SIGNAL Switch_out1_8                    : std_logic;
  SIGNAL FixPt_Relational_Operator18_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_4         : std_logic;
  SIGNAL FixPt_Relational_Operator19_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_4         : std_logic;
  SIGNAL Bitwise_Operator1_out1_13        : std_logic;
  SIGNAL Latch_Off_Active_out1_4          : std_logic;
  SIGNAL Switch2_out1_4                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_14        : std_logic;
  SIGNAL switch_compare_1_27              : std_logic;
  SIGNAL Switch_out1_9                    : std_logic;
  SIGNAL Compare_To_Zero1_out1_4          : std_logic;
  SIGNAL Bitwise_Operator7_out1_4         : std_logic;
  SIGNAL Bitwise_Operator6_out1_4         : std_logic;
  SIGNAL Bitwise_Operator5_out1_4         : std_logic;
  SIGNAL Latch_On_Active_out1_4           : std_logic;
  SIGNAL Switch3_out1_4                   : std_logic;
  SIGNAL switch_compare_1_28              : std_logic;
  SIGNAL Switch1_out1_8                   : std_logic;
  SIGNAL Bitwise_Operator8_out1_4         : std_logic;
  SIGNAL Compare_To_Zero_out1_4           : std_logic;
  SIGNAL Bitwise_Operator_out1_13         : std_logic;
  SIGNAL Switch1_out1_9                   : std_logic;
  SIGNAL Comparators_out1_4               : std_logic;
  SIGNAL Bitwise_Operator_out1_14         : std_logic;
  SIGNAL Relational_Operator34_relop1     : std_logic;
  SIGNAL switch_compare_1_29              : std_logic;
  SIGNAL FixPt_Relational_Operator20_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator21_relop1 : std_logic;
  SIGNAL switch_compare_1_30              : std_logic;
  SIGNAL Bitwise_Operator3_out1_5         : std_logic;
  SIGNAL Cam_Off_5_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_31              : std_logic;
  SIGNAL Cam_On_5_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator8_relop1      : std_logic;
  SIGNAL Relational_Operator15_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_15         : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_5 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_5 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_15        : std_logic;
  SIGNAL Relational_Operator25_relop1     : std_logic;
  SIGNAL switch_compare_1_32              : std_logic;
  SIGNAL Switch_out1_10                   : std_logic;
  SIGNAL FixPt_Relational_Operator22_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_5         : std_logic;
  SIGNAL FixPt_Relational_Operator23_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_5         : std_logic;
  SIGNAL Bitwise_Operator1_out1_16        : std_logic;
  SIGNAL Latch_Off_Active_out1_5          : std_logic;
  SIGNAL Switch2_out1_5                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_17        : std_logic;
  SIGNAL switch_compare_1_33              : std_logic;
  SIGNAL Switch_out1_11                   : std_logic;
  SIGNAL Compare_To_Zero1_out1_5          : std_logic;
  SIGNAL Bitwise_Operator7_out1_5         : std_logic;
  SIGNAL Bitwise_Operator6_out1_5         : std_logic;
  SIGNAL Bitwise_Operator5_out1_5         : std_logic;
  SIGNAL Latch_On_Active_out1_5           : std_logic;
  SIGNAL Switch3_out1_5                   : std_logic;
  SIGNAL switch_compare_1_34              : std_logic;
  SIGNAL Switch1_out1_10                  : std_logic;
  SIGNAL Bitwise_Operator8_out1_5         : std_logic;
  SIGNAL Compare_To_Zero_out1_5           : std_logic;
  SIGNAL Bitwise_Operator_out1_16         : std_logic;
  SIGNAL Switch1_out1_11                  : std_logic;
  SIGNAL Comparators_out1_5               : std_logic;
  SIGNAL Bitwise_Operator_out1_17         : std_logic;
  SIGNAL Relational_Operator35_relop1     : std_logic;
  SIGNAL switch_compare_1_35              : std_logic;
  SIGNAL FixPt_Relational_Operator24_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator25_relop1 : std_logic;
  SIGNAL switch_compare_1_36              : std_logic;
  SIGNAL Bitwise_Operator3_out1_6         : std_logic;
  SIGNAL Cam_Off_6_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_37              : std_logic;
  SIGNAL Cam_On_6_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator9_relop1      : std_logic;
  SIGNAL Relational_Operator16_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_18         : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_6 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_6 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_18        : std_logic;
  SIGNAL Relational_Operator26_relop1     : std_logic;
  SIGNAL switch_compare_1_38              : std_logic;
  SIGNAL Switch_out1_12                   : std_logic;
  SIGNAL FixPt_Relational_Operator26_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_6         : std_logic;
  SIGNAL FixPt_Relational_Operator27_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_6         : std_logic;
  SIGNAL Bitwise_Operator1_out1_19        : std_logic;
  SIGNAL Latch_Off_Active_out1_6          : std_logic;
  SIGNAL Switch2_out1_6                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_20        : std_logic;
  SIGNAL switch_compare_1_39              : std_logic;
  SIGNAL Switch_out1_13                   : std_logic;
  SIGNAL Compare_To_Zero1_out1_6          : std_logic;
  SIGNAL Bitwise_Operator7_out1_6         : std_logic;
  SIGNAL Bitwise_Operator6_out1_6         : std_logic;
  SIGNAL Bitwise_Operator5_out1_6         : std_logic;
  SIGNAL Latch_On_Active_out1_6           : std_logic;
  SIGNAL Switch3_out1_6                   : std_logic;
  SIGNAL switch_compare_1_40              : std_logic;
  SIGNAL Switch1_out1_12                  : std_logic;
  SIGNAL Bitwise_Operator8_out1_6         : std_logic;
  SIGNAL Compare_To_Zero_out1_6           : std_logic;
  SIGNAL Bitwise_Operator_out1_19         : std_logic;
  SIGNAL Switch1_out1_13                  : std_logic;
  SIGNAL Comparators_out1_6               : std_logic;
  SIGNAL Bitwise_Operator_out1_20         : std_logic;
  SIGNAL Relational_Operator36_relop1     : std_logic;
  SIGNAL switch_compare_1_41              : std_logic;
  SIGNAL FixPt_Relational_Operator28_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator29_relop1 : std_logic;
  SIGNAL switch_compare_1_42              : std_logic;
  SIGNAL Bitwise_Operator3_out1_7         : std_logic;
  SIGNAL Cam_Off_7_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_43              : std_logic;
  SIGNAL Cam_On_7_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator10_relop1     : std_logic;
  SIGNAL Relational_Operator17_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_21         : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_7 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_7 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_21        : std_logic;
  SIGNAL Relational_Operator27_relop1     : std_logic;
  SIGNAL switch_compare_1_44              : std_logic;
  SIGNAL Switch_out1_14                   : std_logic;
  SIGNAL FixPt_Relational_Operator30_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_7         : std_logic;
  SIGNAL FixPt_Relational_Operator31_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_7         : std_logic;
  SIGNAL Bitwise_Operator1_out1_22        : std_logic;
  SIGNAL Latch_Off_Active_out1_7          : std_logic;
  SIGNAL Switch2_out1_7                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_23        : std_logic;
  SIGNAL switch_compare_1_45              : std_logic;
  SIGNAL Switch_out1_15                   : std_logic;
  SIGNAL Compare_To_Zero1_out1_7          : std_logic;
  SIGNAL Bitwise_Operator7_out1_7         : std_logic;
  SIGNAL Bitwise_Operator6_out1_7         : std_logic;
  SIGNAL Bitwise_Operator5_out1_7         : std_logic;
  SIGNAL Latch_On_Active_out1_7           : std_logic;
  SIGNAL Switch3_out1_7                   : std_logic;
  SIGNAL switch_compare_1_46              : std_logic;
  SIGNAL Switch1_out1_14                  : std_logic;
  SIGNAL Bitwise_Operator8_out1_7         : std_logic;
  SIGNAL Compare_To_Zero_out1_7           : std_logic;
  SIGNAL Bitwise_Operator_out1_22         : std_logic;
  SIGNAL Switch1_out1_15                  : std_logic;
  SIGNAL Comparators_out1_7               : std_logic;
  SIGNAL Bitwise_Operator_out1_23         : std_logic;
  SIGNAL Relational_Operator37_relop1     : std_logic;
  SIGNAL switch_compare_1_47              : std_logic;
  SIGNAL FixPt_Relational_Operator32_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator33_relop1 : std_logic;
  SIGNAL switch_compare_1_48              : std_logic;
  SIGNAL Bitwise_Operator3_out1_8         : std_logic;
  SIGNAL Cam_Off_8_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_49              : std_logic;
  SIGNAL Cam_On_8_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator19_relop1     : std_logic;
  SIGNAL Relational_Operator18_relop1     : std_logic;
  SIGNAL Bitwise_Operator_out1_24         : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_8 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_8 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_24        : std_logic;
  SIGNAL Relational_Operator28_relop1     : std_logic;
  SIGNAL switch_compare_1_50              : std_logic;
  SIGNAL Switch_out1_16                   : std_logic;
  SIGNAL FixPt_Relational_Operator34_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_8         : std_logic;
  SIGNAL FixPt_Relational_Operator35_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_8         : std_logic;
  SIGNAL Bitwise_Operator1_out1_25        : std_logic;
  SIGNAL Latch_Off_Active_out1_8          : std_logic;
  SIGNAL Switch2_out1_8                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_26        : std_logic;
  SIGNAL switch_compare_1_51              : std_logic;
  SIGNAL Switch_out1_17                   : std_logic;
  SIGNAL Compare_To_Zero1_out1_8          : std_logic;
  SIGNAL Bitwise_Operator7_out1_8         : std_logic;
  SIGNAL Bitwise_Operator6_out1_8         : std_logic;
  SIGNAL Bitwise_Operator5_out1_8         : std_logic;
  SIGNAL Latch_On_Active_out1_8           : std_logic;
  SIGNAL Switch3_out1_8                   : std_logic;
  SIGNAL switch_compare_1_52              : std_logic;
  SIGNAL Switch1_out1_16                  : std_logic;
  SIGNAL Bitwise_Operator8_out1_8         : std_logic;
  SIGNAL Compare_To_Zero_out1_8           : std_logic;
  SIGNAL Bitwise_Operator_out1_25         : std_logic;
  SIGNAL Switch1_out1_17                  : std_logic;
  SIGNAL Comparators_out1_8               : std_logic;
  SIGNAL Bitwise_Operator_out1_26         : std_logic;
  SIGNAL Relational_Operator38_relop1     : std_logic;
  SIGNAL switch_compare_1_53              : std_logic;
  SIGNAL FixPt_Relational_Operator36_relop1 : std_logic;
  SIGNAL FixPt_Relational_Operator37_relop1 : std_logic;
  SIGNAL switch_compare_1_54              : std_logic;
  SIGNAL Bitwise_Operator3_out1_9         : std_logic;
  SIGNAL Cam_Off_9_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL switch_compare_1_55              : std_logic;
  SIGNAL Cam_On_9_unsigned                : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Relational_Operator20_relop1     : std_logic;
  SIGNAL Relational_Operator110_relop1    : std_logic;
  SIGNAL Bitwise_Operator_out1_27         : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1_9 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Unit_Delay_Enabled_Synchronous_out1_9 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bitwise_Operator1_out1_27        : std_logic;
  SIGNAL Relational_Operator29_relop1     : std_logic;
  SIGNAL switch_compare_1_56              : std_logic;
  SIGNAL Switch_out1_18                   : std_logic;
  SIGNAL FixPt_Relational_Operator38_relop1 : std_logic;
  SIGNAL Bitwise_Operator4_out1_9         : std_logic;
  SIGNAL FixPt_Relational_Operator39_relop1 : std_logic;
  SIGNAL Bitwise_Operator2_out1_9         : std_logic;
  SIGNAL Bitwise_Operator1_out1_28        : std_logic;
  SIGNAL Latch_Off_Active_out1_9          : std_logic;
  SIGNAL Switch2_out1_9                   : std_logic;
  SIGNAL Bitwise_Operator1_out1_29        : std_logic;
  SIGNAL switch_compare_1_57              : std_logic;
  SIGNAL Switch_out1_19                   : std_logic;
  SIGNAL Compare_To_Zero1_out1_9          : std_logic;
  SIGNAL Bitwise_Operator7_out1_9         : std_logic;
  SIGNAL Bitwise_Operator6_out1_9         : std_logic;
  SIGNAL Bitwise_Operator5_out1_9         : std_logic;
  SIGNAL Latch_On_Active_out1_9           : std_logic;
  SIGNAL Switch3_out1_9                   : std_logic;
  SIGNAL switch_compare_1_58              : std_logic;
  SIGNAL Switch1_out1_18                  : std_logic;
  SIGNAL Bitwise_Operator8_out1_9         : std_logic;
  SIGNAL Compare_To_Zero_out1_9           : std_logic;
  SIGNAL Bitwise_Operator_out1_28         : std_logic;
  SIGNAL Switch1_out1_19                  : std_logic;
  SIGNAL Comparators_out1_9               : std_logic;
  SIGNAL Bitwise_Operator_out1_29         : std_logic;
  SIGNAL Relational_Operator39_relop1     : std_logic;
  SIGNAL switch_compare_1_59              : std_logic;
  SIGNAL Bitwise_Operator_out1_30         : std_logic;
  SIGNAL Bitwise_Operator1_out1_30        : std_logic;
  SIGNAL Bit_Slice_out1                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Bit_Concat_out1                  : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL U_k_1                            : std_logic;
  SIGNAL U_k_1_1                          : std_logic;
  SIGNAL U_k_1_2                          : std_logic;
  SIGNAL U_k_1_3                          : std_logic;

BEGIN
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)
  -- 
  -- Edge
  -- 
  -- U(k)

  enb <= clk_enable;

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Direction_1 <= '0';
      ELSIF enb = '1' THEN
        Direction_1 <= Direction;
      END IF;
    END IF;
  END PROCESS reduced_process;


  
  FixPt_Relational_Operator_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Enable_1 <= '0';
      ELSIF enb = '1' THEN
        Enable_1 <= Enable;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  
  FixPt_Relational_Operator1_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1 <= '1' WHEN FixPt_Relational_Operator_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1 <=  NOT Direction;

  Cam_Off_0_unsigned <= unsigned(Cam_Off_0);

  
  switch_compare_1_1 <= '1' WHEN FixPt_Relational_Operator_relop1 > '0' ELSE
      '0';

  Cam_On_0_unsigned <= unsigned(Cam_On_0);

  Angle_unsigned <= unsigned(Angle);

  Bitwise_Operator_out1 <= Relational_Operator_relop1 AND Relational_Operator1_relop1;

  
  Relational_Operator1_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1 ELSE
      '0';

  
  Relational_Operator_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1 ELSE
      '0';

  Bitwise_Operator1_out1 <= Relational_Operator_relop1 OR Relational_Operator1_relop1;

  
  Relational_Operator2_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 > Unit_Delay_Enabled_Synchronous1_out1 ELSE
      '0';

  
  switch_compare_1_2 <= '1' WHEN Relational_Operator2_relop1 > '0' ELSE
      '0';

  
  Switch_out1 <= Bitwise_Operator1_out1 WHEN switch_compare_1_2 = '0' ELSE
      Bitwise_Operator_out1;

  Bitwise_Operator4_out1 <= FixPt_Relational_Operator2_relop1 AND Direction;

  Bitwise_Operator2_out1 <= FixPt_Relational_Operator3_relop1 AND Bitwise_Operator3_out1;

  Bitwise_Operator1_out1_1 <= Bitwise_Operator2_out1 OR Bitwise_Operator4_out1;

  
  Switch2_out1 <= Bitwise_Operator1_out1_1 WHEN switch_compare_1_1 = '0' ELSE
      Latch_Off_Active_out1;

  
  switch_compare_1_3 <= '1' WHEN Bitwise_Operator1_out1_2 > '0' ELSE
      '0';

  
  Switch_out1_1 <= Switch2_out1 WHEN switch_compare_1_3 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1 <= FixPt_Relational_Operator3_relop1 AND Direction;

  Bitwise_Operator6_out1 <= FixPt_Relational_Operator2_relop1 AND Bitwise_Operator3_out1;

  Bitwise_Operator5_out1 <= Bitwise_Operator6_out1 OR Bitwise_Operator7_out1;

  
  Switch3_out1 <= Bitwise_Operator5_out1 WHEN switch_compare_1 = '0' ELSE
      Latch_On_Active_out1;

  
  switch_compare_1_4 <= '1' WHEN Bitwise_Operator1_out1_2 > '0' ELSE
      '0';

  
  Switch1_out1 <= Switch3_out1 WHEN switch_compare_1_4 = '0' ELSE
      '1';

  Latch_Off_Active_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1 = '1' THEN
        Latch_Off_Active_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active_process;


  Unit_Delay_Enabled_Synchronous_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= Cam_Off_0_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous_process;


  
  Compare_To_Zero_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_1 <= Compare_To_Zero_out1 AND Compare_To_Zero1_out1;

  Bitwise_Operator1_out1_2 <= FixPt_Relational_Operator1_relop1 OR Bitwise_Operator_out1_1;

  
  FixPt_Relational_Operator2_relop1 <= '1' WHEN Switch1_out1_1 > Comparators_out1 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_2_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1 <= Switch1_out1_1;
      END IF;
    END IF;
  END PROCESS reduced_2_process;


  
  FixPt_Relational_Operator3_relop1 <= '1' WHEN Switch1_out1_1 < Comparators_out1 ELSE
      '0';

  Bitwise_Operator_out1_2 <= FixPt_Relational_Operator3_relop1 OR FixPt_Relational_Operator2_relop1;

  Bitwise_Operator8_out1 <= Bitwise_Operator1_out1_2 OR (Bitwise_Operator_out1_2 OR FixPt_Relational_Operator_relop1);

  Latch_On_Active_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1 = '1' THEN
        Latch_On_Active_out1 <= Switch_out1_1;
      END IF;
    END IF;
  END PROCESS Latch_On_Active_process;


  Unit_Delay_Enabled_Synchronous1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1 <= Cam_On_0_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_process;


  
  Relational_Operator3_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1 = Unit_Delay_Enabled_Synchronous_out1 ELSE
      '0';

  
  switch_compare_1_5 <= '1' WHEN Relational_Operator3_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_1 <= Switch_out1 WHEN switch_compare_1_5 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator4_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator5_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_6 <= '1' WHEN FixPt_Relational_Operator4_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_1 <=  NOT Direction;

  Cam_Off_1_unsigned <= unsigned(Cam_Off_1);

  
  switch_compare_1_7 <= '1' WHEN FixPt_Relational_Operator4_relop1 > '0' ELSE
      '0';

  Cam_On_1_unsigned <= unsigned(Cam_On_1);

  Bitwise_Operator_out1_3 <= Relational_Operator4_relop1 AND Relational_Operator11_relop1;

  
  Relational_Operator11_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_1 ELSE
      '0';

  
  Relational_Operator4_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_1 ELSE
      '0';

  Bitwise_Operator1_out1_3 <= Relational_Operator4_relop1 OR Relational_Operator11_relop1;

  
  Relational_Operator21_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_1 > Unit_Delay_Enabled_Synchronous1_out1_1 ELSE
      '0';

  
  switch_compare_1_8 <= '1' WHEN Relational_Operator21_relop1 > '0' ELSE
      '0';

  
  Switch_out1_2 <= Bitwise_Operator1_out1_3 WHEN switch_compare_1_8 = '0' ELSE
      Bitwise_Operator_out1_3;

  Bitwise_Operator4_out1_1 <= FixPt_Relational_Operator6_relop1 AND Direction;

  Bitwise_Operator2_out1_1 <= FixPt_Relational_Operator7_relop1 AND Bitwise_Operator3_out1_1;

  Bitwise_Operator1_out1_4 <= Bitwise_Operator2_out1_1 OR Bitwise_Operator4_out1_1;

  
  Switch2_out1_1 <= Bitwise_Operator1_out1_4 WHEN switch_compare_1_7 = '0' ELSE
      Latch_Off_Active_out1_1;

  
  switch_compare_1_9 <= '1' WHEN Bitwise_Operator1_out1_5 > '0' ELSE
      '0';

  
  Switch_out1_3 <= Switch2_out1_1 WHEN switch_compare_1_9 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_1 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_1 <= FixPt_Relational_Operator7_relop1 AND Direction;

  Bitwise_Operator6_out1_1 <= FixPt_Relational_Operator6_relop1 AND Bitwise_Operator3_out1_1;

  Bitwise_Operator5_out1_1 <= Bitwise_Operator6_out1_1 OR Bitwise_Operator7_out1_1;

  
  Switch3_out1_1 <= Bitwise_Operator5_out1_1 WHEN switch_compare_1_6 = '0' ELSE
      Latch_On_Active_out1_1;

  
  switch_compare_1_10 <= '1' WHEN Bitwise_Operator1_out1_5 > '0' ELSE
      '0';

  
  Switch1_out1_2 <= Switch3_out1_1 WHEN switch_compare_1_10 = '0' ELSE
      '1';

  Latch_Off_Active1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_1 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_1 = '1' THEN
        Latch_Off_Active_out1_1 <= Switch1_out1_2;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active1_process;


  Unit_Delay_Enabled_Synchronous2_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_1 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_1 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_1 <= Cam_Off_1_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous2_process;


  
  Compare_To_Zero_out1_1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_1 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_4 <= Compare_To_Zero_out1_1 AND Compare_To_Zero1_out1_1;

  Bitwise_Operator1_out1_5 <= FixPt_Relational_Operator5_relop1 OR Bitwise_Operator_out1_4;

  
  FixPt_Relational_Operator6_relop1 <= '1' WHEN Switch1_out1_3 > Comparators_out1_1 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_3_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_1 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_1 <= Switch1_out1_3;
      END IF;
    END IF;
  END PROCESS reduced_3_process;


  
  FixPt_Relational_Operator7_relop1 <= '1' WHEN Switch1_out1_3 < Comparators_out1_1 ELSE
      '0';

  Bitwise_Operator_out1_5 <= FixPt_Relational_Operator7_relop1 OR FixPt_Relational_Operator6_relop1;

  Bitwise_Operator8_out1_1 <= Bitwise_Operator1_out1_5 OR (Bitwise_Operator_out1_5 OR FixPt_Relational_Operator4_relop1);

  Latch_On_Active1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_1 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_1 = '1' THEN
        Latch_On_Active_out1_1 <= Switch_out1_3;
      END IF;
    END IF;
  END PROCESS Latch_On_Active1_process;


  Unit_Delay_Enabled_Synchronous11_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_1 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_1 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_1 <= Cam_On_1_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous11_process;


  
  Relational_Operator31_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_1 = Unit_Delay_Enabled_Synchronous_out1_1 ELSE
      '0';

  
  switch_compare_1_11 <= '1' WHEN Relational_Operator31_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_3 <= Switch_out1_2 WHEN switch_compare_1_11 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator8_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator9_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_12 <= '1' WHEN FixPt_Relational_Operator8_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_2 <=  NOT Direction;

  Cam_Off_2_unsigned <= unsigned(Cam_Off_2);

  
  switch_compare_1_13 <= '1' WHEN FixPt_Relational_Operator8_relop1 > '0' ELSE
      '0';

  Cam_On_2_unsigned <= unsigned(Cam_On_2);

  Bitwise_Operator_out1_6 <= Relational_Operator5_relop1 AND Relational_Operator12_relop1;

  
  Relational_Operator12_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_2 ELSE
      '0';

  
  Relational_Operator5_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_2 ELSE
      '0';

  Bitwise_Operator1_out1_6 <= Relational_Operator5_relop1 OR Relational_Operator12_relop1;

  
  Relational_Operator22_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_2 > Unit_Delay_Enabled_Synchronous1_out1_2 ELSE
      '0';

  
  switch_compare_1_14 <= '1' WHEN Relational_Operator22_relop1 > '0' ELSE
      '0';

  
  Switch_out1_4 <= Bitwise_Operator1_out1_6 WHEN switch_compare_1_14 = '0' ELSE
      Bitwise_Operator_out1_6;

  Bitwise_Operator4_out1_2 <= FixPt_Relational_Operator10_relop1 AND Direction;

  Bitwise_Operator2_out1_2 <= FixPt_Relational_Operator11_relop1 AND Bitwise_Operator3_out1_2;

  Bitwise_Operator1_out1_7 <= Bitwise_Operator2_out1_2 OR Bitwise_Operator4_out1_2;

  
  Switch2_out1_2 <= Bitwise_Operator1_out1_7 WHEN switch_compare_1_13 = '0' ELSE
      Latch_Off_Active_out1_2;

  
  switch_compare_1_15 <= '1' WHEN Bitwise_Operator1_out1_8 > '0' ELSE
      '0';

  
  Switch_out1_5 <= Switch2_out1_2 WHEN switch_compare_1_15 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_2 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_2 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_2 <= FixPt_Relational_Operator11_relop1 AND Direction;

  Bitwise_Operator6_out1_2 <= FixPt_Relational_Operator10_relop1 AND Bitwise_Operator3_out1_2;

  Bitwise_Operator5_out1_2 <= Bitwise_Operator6_out1_2 OR Bitwise_Operator7_out1_2;

  
  Switch3_out1_2 <= Bitwise_Operator5_out1_2 WHEN switch_compare_1_12 = '0' ELSE
      Latch_On_Active_out1_2;

  
  switch_compare_1_16 <= '1' WHEN Bitwise_Operator1_out1_8 > '0' ELSE
      '0';

  
  Switch1_out1_4 <= Switch3_out1_2 WHEN switch_compare_1_16 = '0' ELSE
      '1';

  Latch_Off_Active2_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_2 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_2 = '1' THEN
        Latch_Off_Active_out1_2 <= Switch1_out1_4;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active2_process;


  Unit_Delay_Enabled_Synchronous3_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_2 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_2 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_2 <= Cam_Off_2_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous3_process;


  
  Compare_To_Zero_out1_2 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_2 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_7 <= Compare_To_Zero_out1_2 AND Compare_To_Zero1_out1_2;

  Bitwise_Operator1_out1_8 <= FixPt_Relational_Operator9_relop1 OR Bitwise_Operator_out1_7;

  
  FixPt_Relational_Operator10_relop1 <= '1' WHEN Switch1_out1_5 > Comparators_out1_2 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_4_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_2 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_2 <= Switch1_out1_5;
      END IF;
    END IF;
  END PROCESS reduced_4_process;


  
  FixPt_Relational_Operator11_relop1 <= '1' WHEN Switch1_out1_5 < Comparators_out1_2 ELSE
      '0';

  Bitwise_Operator_out1_8 <= FixPt_Relational_Operator11_relop1 OR FixPt_Relational_Operator10_relop1;

  Bitwise_Operator8_out1_2 <= Bitwise_Operator1_out1_8 OR (Bitwise_Operator_out1_8 OR FixPt_Relational_Operator8_relop1);

  Latch_On_Active2_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_2 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_2 = '1' THEN
        Latch_On_Active_out1_2 <= Switch_out1_5;
      END IF;
    END IF;
  END PROCESS Latch_On_Active2_process;


  Unit_Delay_Enabled_Synchronous12_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_2 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_2 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_2 <= Cam_On_2_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous12_process;


  
  Relational_Operator32_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_2 = Unit_Delay_Enabled_Synchronous_out1_2 ELSE
      '0';

  
  switch_compare_1_17 <= '1' WHEN Relational_Operator32_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_5 <= Switch_out1_4 WHEN switch_compare_1_17 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator12_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator13_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_18 <= '1' WHEN FixPt_Relational_Operator12_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_3 <=  NOT Direction;

  Cam_Off_3_unsigned <= unsigned(Cam_Off_3);

  
  switch_compare_1_19 <= '1' WHEN FixPt_Relational_Operator12_relop1 > '0' ELSE
      '0';

  Cam_On_3_unsigned <= unsigned(Cam_On_3);

  Bitwise_Operator_out1_9 <= Relational_Operator6_relop1 AND Relational_Operator13_relop1;

  
  Relational_Operator13_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_3 ELSE
      '0';

  
  Relational_Operator6_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_3 ELSE
      '0';

  Bitwise_Operator1_out1_9 <= Relational_Operator6_relop1 OR Relational_Operator13_relop1;

  
  Relational_Operator23_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_3 > Unit_Delay_Enabled_Synchronous1_out1_3 ELSE
      '0';

  
  switch_compare_1_20 <= '1' WHEN Relational_Operator23_relop1 > '0' ELSE
      '0';

  
  Switch_out1_6 <= Bitwise_Operator1_out1_9 WHEN switch_compare_1_20 = '0' ELSE
      Bitwise_Operator_out1_9;

  Bitwise_Operator4_out1_3 <= FixPt_Relational_Operator14_relop1 AND Direction;

  Bitwise_Operator2_out1_3 <= FixPt_Relational_Operator15_relop1 AND Bitwise_Operator3_out1_3;

  Bitwise_Operator1_out1_10 <= Bitwise_Operator2_out1_3 OR Bitwise_Operator4_out1_3;

  
  Switch2_out1_3 <= Bitwise_Operator1_out1_10 WHEN switch_compare_1_19 = '0' ELSE
      Latch_Off_Active_out1_3;

  
  switch_compare_1_21 <= '1' WHEN Bitwise_Operator1_out1_11 > '0' ELSE
      '0';

  
  Switch_out1_7 <= Switch2_out1_3 WHEN switch_compare_1_21 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_3 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_3 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_3 <= FixPt_Relational_Operator15_relop1 AND Direction;

  Bitwise_Operator6_out1_3 <= FixPt_Relational_Operator14_relop1 AND Bitwise_Operator3_out1_3;

  Bitwise_Operator5_out1_3 <= Bitwise_Operator6_out1_3 OR Bitwise_Operator7_out1_3;

  
  Switch3_out1_3 <= Bitwise_Operator5_out1_3 WHEN switch_compare_1_18 = '0' ELSE
      Latch_On_Active_out1_3;

  
  switch_compare_1_22 <= '1' WHEN Bitwise_Operator1_out1_11 > '0' ELSE
      '0';

  
  Switch1_out1_6 <= Switch3_out1_3 WHEN switch_compare_1_22 = '0' ELSE
      '1';

  Latch_Off_Active3_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_3 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_3 = '1' THEN
        Latch_Off_Active_out1_3 <= Switch1_out1_6;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active3_process;


  Unit_Delay_Enabled_Synchronous4_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_3 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_3 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_3 <= Cam_Off_3_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous4_process;


  
  Compare_To_Zero_out1_3 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_3 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_10 <= Compare_To_Zero_out1_3 AND Compare_To_Zero1_out1_3;

  Bitwise_Operator1_out1_11 <= FixPt_Relational_Operator13_relop1 OR Bitwise_Operator_out1_10;

  
  FixPt_Relational_Operator14_relop1 <= '1' WHEN Switch1_out1_7 > Comparators_out1_3 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_5_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_3 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_3 <= Switch1_out1_7;
      END IF;
    END IF;
  END PROCESS reduced_5_process;


  
  FixPt_Relational_Operator15_relop1 <= '1' WHEN Switch1_out1_7 < Comparators_out1_3 ELSE
      '0';

  Bitwise_Operator_out1_11 <= FixPt_Relational_Operator15_relop1 OR FixPt_Relational_Operator14_relop1;

  Bitwise_Operator8_out1_3 <= Bitwise_Operator1_out1_11 OR (Bitwise_Operator_out1_11 OR FixPt_Relational_Operator12_relop1);

  Latch_On_Active3_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_3 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_3 = '1' THEN
        Latch_On_Active_out1_3 <= Switch_out1_7;
      END IF;
    END IF;
  END PROCESS Latch_On_Active3_process;


  Unit_Delay_Enabled_Synchronous13_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_3 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_3 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_3 <= Cam_On_3_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous13_process;


  
  Relational_Operator33_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_3 = Unit_Delay_Enabled_Synchronous_out1_3 ELSE
      '0';

  
  switch_compare_1_23 <= '1' WHEN Relational_Operator33_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_7 <= Switch_out1_6 WHEN switch_compare_1_23 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator16_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator17_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_24 <= '1' WHEN FixPt_Relational_Operator16_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_4 <=  NOT Direction;

  Cam_Off_4_unsigned <= unsigned(Cam_Off_4);

  
  switch_compare_1_25 <= '1' WHEN FixPt_Relational_Operator16_relop1 > '0' ELSE
      '0';

  Cam_On_4_unsigned <= unsigned(Cam_On_4);

  Bitwise_Operator_out1_12 <= Relational_Operator7_relop1 AND Relational_Operator14_relop1;

  
  Relational_Operator14_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_4 ELSE
      '0';

  
  Relational_Operator7_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_4 ELSE
      '0';

  Bitwise_Operator1_out1_12 <= Relational_Operator7_relop1 OR Relational_Operator14_relop1;

  
  Relational_Operator24_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_4 > Unit_Delay_Enabled_Synchronous1_out1_4 ELSE
      '0';

  
  switch_compare_1_26 <= '1' WHEN Relational_Operator24_relop1 > '0' ELSE
      '0';

  
  Switch_out1_8 <= Bitwise_Operator1_out1_12 WHEN switch_compare_1_26 = '0' ELSE
      Bitwise_Operator_out1_12;

  Bitwise_Operator4_out1_4 <= FixPt_Relational_Operator18_relop1 AND Direction;

  Bitwise_Operator2_out1_4 <= FixPt_Relational_Operator19_relop1 AND Bitwise_Operator3_out1_4;

  Bitwise_Operator1_out1_13 <= Bitwise_Operator2_out1_4 OR Bitwise_Operator4_out1_4;

  
  Switch2_out1_4 <= Bitwise_Operator1_out1_13 WHEN switch_compare_1_25 = '0' ELSE
      Latch_Off_Active_out1_4;

  
  switch_compare_1_27 <= '1' WHEN Bitwise_Operator1_out1_14 > '0' ELSE
      '0';

  
  Switch_out1_9 <= Switch2_out1_4 WHEN switch_compare_1_27 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_4 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_4 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_4 <= FixPt_Relational_Operator19_relop1 AND Direction;

  Bitwise_Operator6_out1_4 <= FixPt_Relational_Operator18_relop1 AND Bitwise_Operator3_out1_4;

  Bitwise_Operator5_out1_4 <= Bitwise_Operator6_out1_4 OR Bitwise_Operator7_out1_4;

  
  Switch3_out1_4 <= Bitwise_Operator5_out1_4 WHEN switch_compare_1_24 = '0' ELSE
      Latch_On_Active_out1_4;

  
  switch_compare_1_28 <= '1' WHEN Bitwise_Operator1_out1_14 > '0' ELSE
      '0';

  
  Switch1_out1_8 <= Switch3_out1_4 WHEN switch_compare_1_28 = '0' ELSE
      '1';

  Latch_Off_Active4_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_4 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_4 = '1' THEN
        Latch_Off_Active_out1_4 <= Switch1_out1_8;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active4_process;


  Unit_Delay_Enabled_Synchronous5_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_4 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_4 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_4 <= Cam_Off_4_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous5_process;


  
  Compare_To_Zero_out1_4 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_4 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_13 <= Compare_To_Zero_out1_4 AND Compare_To_Zero1_out1_4;

  Bitwise_Operator1_out1_14 <= FixPt_Relational_Operator17_relop1 OR Bitwise_Operator_out1_13;

  
  FixPt_Relational_Operator18_relop1 <= '1' WHEN Switch1_out1_9 > Comparators_out1_4 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_6_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_4 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_4 <= Switch1_out1_9;
      END IF;
    END IF;
  END PROCESS reduced_6_process;


  
  FixPt_Relational_Operator19_relop1 <= '1' WHEN Switch1_out1_9 < Comparators_out1_4 ELSE
      '0';

  Bitwise_Operator_out1_14 <= FixPt_Relational_Operator19_relop1 OR FixPt_Relational_Operator18_relop1;

  Bitwise_Operator8_out1_4 <= Bitwise_Operator1_out1_14 OR (Bitwise_Operator_out1_14 OR FixPt_Relational_Operator16_relop1);

  Latch_On_Active4_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_4 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_4 = '1' THEN
        Latch_On_Active_out1_4 <= Switch_out1_9;
      END IF;
    END IF;
  END PROCESS Latch_On_Active4_process;


  Unit_Delay_Enabled_Synchronous14_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_4 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_4 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_4 <= Cam_On_4_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous14_process;


  
  Relational_Operator34_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_4 = Unit_Delay_Enabled_Synchronous_out1_4 ELSE
      '0';

  
  switch_compare_1_29 <= '1' WHEN Relational_Operator34_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_9 <= Switch_out1_8 WHEN switch_compare_1_29 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator20_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator21_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_30 <= '1' WHEN FixPt_Relational_Operator20_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_5 <=  NOT Direction;

  Cam_Off_5_unsigned <= unsigned(Cam_Off_5);

  
  switch_compare_1_31 <= '1' WHEN FixPt_Relational_Operator20_relop1 > '0' ELSE
      '0';

  Cam_On_5_unsigned <= unsigned(Cam_On_5);

  Bitwise_Operator_out1_15 <= Relational_Operator8_relop1 AND Relational_Operator15_relop1;

  
  Relational_Operator15_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_5 ELSE
      '0';

  
  Relational_Operator8_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_5 ELSE
      '0';

  Bitwise_Operator1_out1_15 <= Relational_Operator8_relop1 OR Relational_Operator15_relop1;

  
  Relational_Operator25_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_5 > Unit_Delay_Enabled_Synchronous1_out1_5 ELSE
      '0';

  
  switch_compare_1_32 <= '1' WHEN Relational_Operator25_relop1 > '0' ELSE
      '0';

  
  Switch_out1_10 <= Bitwise_Operator1_out1_15 WHEN switch_compare_1_32 = '0' ELSE
      Bitwise_Operator_out1_15;

  Bitwise_Operator4_out1_5 <= FixPt_Relational_Operator22_relop1 AND Direction;

  Bitwise_Operator2_out1_5 <= FixPt_Relational_Operator23_relop1 AND Bitwise_Operator3_out1_5;

  Bitwise_Operator1_out1_16 <= Bitwise_Operator2_out1_5 OR Bitwise_Operator4_out1_5;

  
  Switch2_out1_5 <= Bitwise_Operator1_out1_16 WHEN switch_compare_1_31 = '0' ELSE
      Latch_Off_Active_out1_5;

  
  switch_compare_1_33 <= '1' WHEN Bitwise_Operator1_out1_17 > '0' ELSE
      '0';

  
  Switch_out1_11 <= Switch2_out1_5 WHEN switch_compare_1_33 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_5 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_5 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_5 <= FixPt_Relational_Operator23_relop1 AND Direction;

  Bitwise_Operator6_out1_5 <= FixPt_Relational_Operator22_relop1 AND Bitwise_Operator3_out1_5;

  Bitwise_Operator5_out1_5 <= Bitwise_Operator6_out1_5 OR Bitwise_Operator7_out1_5;

  
  Switch3_out1_5 <= Bitwise_Operator5_out1_5 WHEN switch_compare_1_30 = '0' ELSE
      Latch_On_Active_out1_5;

  
  switch_compare_1_34 <= '1' WHEN Bitwise_Operator1_out1_17 > '0' ELSE
      '0';

  
  Switch1_out1_10 <= Switch3_out1_5 WHEN switch_compare_1_34 = '0' ELSE
      '1';

  Latch_Off_Active5_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_5 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_5 = '1' THEN
        Latch_Off_Active_out1_5 <= Switch1_out1_10;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active5_process;


  Unit_Delay_Enabled_Synchronous6_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_5 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_5 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_5 <= Cam_Off_5_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous6_process;


  
  Compare_To_Zero_out1_5 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_5 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_16 <= Compare_To_Zero_out1_5 AND Compare_To_Zero1_out1_5;

  Bitwise_Operator1_out1_17 <= FixPt_Relational_Operator21_relop1 OR Bitwise_Operator_out1_16;

  
  FixPt_Relational_Operator22_relop1 <= '1' WHEN Switch1_out1_11 > Comparators_out1_5 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_7_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_5 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_5 <= Switch1_out1_11;
      END IF;
    END IF;
  END PROCESS reduced_7_process;


  
  FixPt_Relational_Operator23_relop1 <= '1' WHEN Switch1_out1_11 < Comparators_out1_5 ELSE
      '0';

  Bitwise_Operator_out1_17 <= FixPt_Relational_Operator23_relop1 OR FixPt_Relational_Operator22_relop1;

  Bitwise_Operator8_out1_5 <= Bitwise_Operator1_out1_17 OR (Bitwise_Operator_out1_17 OR FixPt_Relational_Operator20_relop1);

  Latch_On_Active5_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_5 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_5 = '1' THEN
        Latch_On_Active_out1_5 <= Switch_out1_11;
      END IF;
    END IF;
  END PROCESS Latch_On_Active5_process;


  Unit_Delay_Enabled_Synchronous15_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_5 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_5 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_5 <= Cam_On_5_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous15_process;


  
  Relational_Operator35_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_5 = Unit_Delay_Enabled_Synchronous_out1_5 ELSE
      '0';

  
  switch_compare_1_35 <= '1' WHEN Relational_Operator35_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_11 <= Switch_out1_10 WHEN switch_compare_1_35 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator24_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator25_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_36 <= '1' WHEN FixPt_Relational_Operator24_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_6 <=  NOT Direction;

  Cam_Off_6_unsigned <= unsigned(Cam_Off_6);

  
  switch_compare_1_37 <= '1' WHEN FixPt_Relational_Operator24_relop1 > '0' ELSE
      '0';

  Cam_On_6_unsigned <= unsigned(Cam_On_6);

  Bitwise_Operator_out1_18 <= Relational_Operator9_relop1 AND Relational_Operator16_relop1;

  
  Relational_Operator16_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_6 ELSE
      '0';

  
  Relational_Operator9_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_6 ELSE
      '0';

  Bitwise_Operator1_out1_18 <= Relational_Operator9_relop1 OR Relational_Operator16_relop1;

  
  Relational_Operator26_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_6 > Unit_Delay_Enabled_Synchronous1_out1_6 ELSE
      '0';

  
  switch_compare_1_38 <= '1' WHEN Relational_Operator26_relop1 > '0' ELSE
      '0';

  
  Switch_out1_12 <= Bitwise_Operator1_out1_18 WHEN switch_compare_1_38 = '0' ELSE
      Bitwise_Operator_out1_18;

  Bitwise_Operator4_out1_6 <= FixPt_Relational_Operator26_relop1 AND Direction;

  Bitwise_Operator2_out1_6 <= FixPt_Relational_Operator27_relop1 AND Bitwise_Operator3_out1_6;

  Bitwise_Operator1_out1_19 <= Bitwise_Operator2_out1_6 OR Bitwise_Operator4_out1_6;

  
  Switch2_out1_6 <= Bitwise_Operator1_out1_19 WHEN switch_compare_1_37 = '0' ELSE
      Latch_Off_Active_out1_6;

  
  switch_compare_1_39 <= '1' WHEN Bitwise_Operator1_out1_20 > '0' ELSE
      '0';

  
  Switch_out1_13 <= Switch2_out1_6 WHEN switch_compare_1_39 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_6 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_6 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_6 <= FixPt_Relational_Operator27_relop1 AND Direction;

  Bitwise_Operator6_out1_6 <= FixPt_Relational_Operator26_relop1 AND Bitwise_Operator3_out1_6;

  Bitwise_Operator5_out1_6 <= Bitwise_Operator6_out1_6 OR Bitwise_Operator7_out1_6;

  
  Switch3_out1_6 <= Bitwise_Operator5_out1_6 WHEN switch_compare_1_36 = '0' ELSE
      Latch_On_Active_out1_6;

  
  switch_compare_1_40 <= '1' WHEN Bitwise_Operator1_out1_20 > '0' ELSE
      '0';

  
  Switch1_out1_12 <= Switch3_out1_6 WHEN switch_compare_1_40 = '0' ELSE
      '1';

  Latch_Off_Active6_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_6 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_6 = '1' THEN
        Latch_Off_Active_out1_6 <= Switch1_out1_12;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active6_process;


  Unit_Delay_Enabled_Synchronous7_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_6 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_6 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_6 <= Cam_Off_6_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous7_process;


  
  Compare_To_Zero_out1_6 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_6 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_19 <= Compare_To_Zero_out1_6 AND Compare_To_Zero1_out1_6;

  Bitwise_Operator1_out1_20 <= FixPt_Relational_Operator25_relop1 OR Bitwise_Operator_out1_19;

  
  FixPt_Relational_Operator26_relop1 <= '1' WHEN Switch1_out1_13 > Comparators_out1_6 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_8_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_6 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_6 <= Switch1_out1_13;
      END IF;
    END IF;
  END PROCESS reduced_8_process;


  
  FixPt_Relational_Operator27_relop1 <= '1' WHEN Switch1_out1_13 < Comparators_out1_6 ELSE
      '0';

  Bitwise_Operator_out1_20 <= FixPt_Relational_Operator27_relop1 OR FixPt_Relational_Operator26_relop1;

  Bitwise_Operator8_out1_6 <= Bitwise_Operator1_out1_20 OR (Bitwise_Operator_out1_20 OR FixPt_Relational_Operator24_relop1);

  Latch_On_Active6_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_6 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_6 = '1' THEN
        Latch_On_Active_out1_6 <= Switch_out1_13;
      END IF;
    END IF;
  END PROCESS Latch_On_Active6_process;


  Unit_Delay_Enabled_Synchronous16_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_6 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_6 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_6 <= Cam_On_6_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous16_process;


  
  Relational_Operator36_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_6 = Unit_Delay_Enabled_Synchronous_out1_6 ELSE
      '0';

  
  switch_compare_1_41 <= '1' WHEN Relational_Operator36_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_13 <= Switch_out1_12 WHEN switch_compare_1_41 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator28_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator29_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_42 <= '1' WHEN FixPt_Relational_Operator28_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_7 <=  NOT Direction;

  Cam_Off_7_unsigned <= unsigned(Cam_Off_7);

  
  switch_compare_1_43 <= '1' WHEN FixPt_Relational_Operator28_relop1 > '0' ELSE
      '0';

  Cam_On_7_unsigned <= unsigned(Cam_On_7);

  Bitwise_Operator_out1_21 <= Relational_Operator10_relop1 AND Relational_Operator17_relop1;

  
  Relational_Operator17_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_7 ELSE
      '0';

  
  Relational_Operator10_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_7 ELSE
      '0';

  Bitwise_Operator1_out1_21 <= Relational_Operator10_relop1 OR Relational_Operator17_relop1;

  
  Relational_Operator27_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_7 > Unit_Delay_Enabled_Synchronous1_out1_7 ELSE
      '0';

  
  switch_compare_1_44 <= '1' WHEN Relational_Operator27_relop1 > '0' ELSE
      '0';

  
  Switch_out1_14 <= Bitwise_Operator1_out1_21 WHEN switch_compare_1_44 = '0' ELSE
      Bitwise_Operator_out1_21;

  Bitwise_Operator4_out1_7 <= FixPt_Relational_Operator30_relop1 AND Direction;

  Bitwise_Operator2_out1_7 <= FixPt_Relational_Operator31_relop1 AND Bitwise_Operator3_out1_7;

  Bitwise_Operator1_out1_22 <= Bitwise_Operator2_out1_7 OR Bitwise_Operator4_out1_7;

  
  Switch2_out1_7 <= Bitwise_Operator1_out1_22 WHEN switch_compare_1_43 = '0' ELSE
      Latch_Off_Active_out1_7;

  
  switch_compare_1_45 <= '1' WHEN Bitwise_Operator1_out1_23 > '0' ELSE
      '0';

  
  Switch_out1_15 <= Switch2_out1_7 WHEN switch_compare_1_45 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_7 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_7 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_7 <= FixPt_Relational_Operator31_relop1 AND Direction;

  Bitwise_Operator6_out1_7 <= FixPt_Relational_Operator30_relop1 AND Bitwise_Operator3_out1_7;

  Bitwise_Operator5_out1_7 <= Bitwise_Operator6_out1_7 OR Bitwise_Operator7_out1_7;

  
  Switch3_out1_7 <= Bitwise_Operator5_out1_7 WHEN switch_compare_1_42 = '0' ELSE
      Latch_On_Active_out1_7;

  
  switch_compare_1_46 <= '1' WHEN Bitwise_Operator1_out1_23 > '0' ELSE
      '0';

  
  Switch1_out1_14 <= Switch3_out1_7 WHEN switch_compare_1_46 = '0' ELSE
      '1';

  Latch_Off_Active7_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_7 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_7 = '1' THEN
        Latch_Off_Active_out1_7 <= Switch1_out1_14;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active7_process;


  Unit_Delay_Enabled_Synchronous8_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_7 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_7 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_7 <= Cam_Off_7_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous8_process;


  
  Compare_To_Zero_out1_7 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_7 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_22 <= Compare_To_Zero_out1_7 AND Compare_To_Zero1_out1_7;

  Bitwise_Operator1_out1_23 <= FixPt_Relational_Operator29_relop1 OR Bitwise_Operator_out1_22;

  
  FixPt_Relational_Operator30_relop1 <= '1' WHEN Switch1_out1_15 > Comparators_out1_7 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_9_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_7 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_7 <= Switch1_out1_15;
      END IF;
    END IF;
  END PROCESS reduced_9_process;


  
  FixPt_Relational_Operator31_relop1 <= '1' WHEN Switch1_out1_15 < Comparators_out1_7 ELSE
      '0';

  Bitwise_Operator_out1_23 <= FixPt_Relational_Operator31_relop1 OR FixPt_Relational_Operator30_relop1;

  Bitwise_Operator8_out1_7 <= Bitwise_Operator1_out1_23 OR (Bitwise_Operator_out1_23 OR FixPt_Relational_Operator28_relop1);

  Latch_On_Active7_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_7 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_7 = '1' THEN
        Latch_On_Active_out1_7 <= Switch_out1_15;
      END IF;
    END IF;
  END PROCESS Latch_On_Active7_process;


  Unit_Delay_Enabled_Synchronous17_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_7 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_7 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_7 <= Cam_On_7_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous17_process;


  
  Relational_Operator37_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_7 = Unit_Delay_Enabled_Synchronous_out1_7 ELSE
      '0';

  
  switch_compare_1_47 <= '1' WHEN Relational_Operator37_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_15 <= Switch_out1_14 WHEN switch_compare_1_47 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator32_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator33_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_48 <= '1' WHEN FixPt_Relational_Operator32_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_8 <=  NOT Direction;

  Cam_Off_8_unsigned <= unsigned(Cam_Off_8);

  
  switch_compare_1_49 <= '1' WHEN FixPt_Relational_Operator32_relop1 > '0' ELSE
      '0';

  Cam_On_8_unsigned <= unsigned(Cam_On_8);

  Bitwise_Operator_out1_24 <= Relational_Operator19_relop1 AND Relational_Operator18_relop1;

  
  Relational_Operator18_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_8 ELSE
      '0';

  
  Relational_Operator19_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_8 ELSE
      '0';

  Bitwise_Operator1_out1_24 <= Relational_Operator19_relop1 OR Relational_Operator18_relop1;

  
  Relational_Operator28_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_8 > Unit_Delay_Enabled_Synchronous1_out1_8 ELSE
      '0';

  
  switch_compare_1_50 <= '1' WHEN Relational_Operator28_relop1 > '0' ELSE
      '0';

  
  Switch_out1_16 <= Bitwise_Operator1_out1_24 WHEN switch_compare_1_50 = '0' ELSE
      Bitwise_Operator_out1_24;

  Bitwise_Operator4_out1_8 <= FixPt_Relational_Operator34_relop1 AND Direction;

  Bitwise_Operator2_out1_8 <= FixPt_Relational_Operator35_relop1 AND Bitwise_Operator3_out1_8;

  Bitwise_Operator1_out1_25 <= Bitwise_Operator2_out1_8 OR Bitwise_Operator4_out1_8;

  
  Switch2_out1_8 <= Bitwise_Operator1_out1_25 WHEN switch_compare_1_49 = '0' ELSE
      Latch_Off_Active_out1_8;

  
  switch_compare_1_51 <= '1' WHEN Bitwise_Operator1_out1_26 > '0' ELSE
      '0';

  
  Switch_out1_17 <= Switch2_out1_8 WHEN switch_compare_1_51 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_8 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_8 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_8 <= FixPt_Relational_Operator35_relop1 AND Direction;

  Bitwise_Operator6_out1_8 <= FixPt_Relational_Operator34_relop1 AND Bitwise_Operator3_out1_8;

  Bitwise_Operator5_out1_8 <= Bitwise_Operator6_out1_8 OR Bitwise_Operator7_out1_8;

  
  Switch3_out1_8 <= Bitwise_Operator5_out1_8 WHEN switch_compare_1_48 = '0' ELSE
      Latch_On_Active_out1_8;

  
  switch_compare_1_52 <= '1' WHEN Bitwise_Operator1_out1_26 > '0' ELSE
      '0';

  
  Switch1_out1_16 <= Switch3_out1_8 WHEN switch_compare_1_52 = '0' ELSE
      '1';

  Latch_Off_Active8_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_8 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_8 = '1' THEN
        Latch_Off_Active_out1_8 <= Switch1_out1_16;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active8_process;


  Unit_Delay_Enabled_Synchronous9_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_8 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_8 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_8 <= Cam_Off_8_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous9_process;


  
  Compare_To_Zero_out1_8 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_8 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_25 <= Compare_To_Zero_out1_8 AND Compare_To_Zero1_out1_8;

  Bitwise_Operator1_out1_26 <= FixPt_Relational_Operator33_relop1 OR Bitwise_Operator_out1_25;

  
  FixPt_Relational_Operator34_relop1 <= '1' WHEN Switch1_out1_17 > Comparators_out1_8 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_10_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_8 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_8 <= Switch1_out1_17;
      END IF;
    END IF;
  END PROCESS reduced_10_process;


  
  FixPt_Relational_Operator35_relop1 <= '1' WHEN Switch1_out1_17 < Comparators_out1_8 ELSE
      '0';

  Bitwise_Operator_out1_26 <= FixPt_Relational_Operator35_relop1 OR FixPt_Relational_Operator34_relop1;

  Bitwise_Operator8_out1_8 <= Bitwise_Operator1_out1_26 OR (Bitwise_Operator_out1_26 OR FixPt_Relational_Operator32_relop1);

  Latch_On_Active8_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_8 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_8 = '1' THEN
        Latch_On_Active_out1_8 <= Switch_out1_17;
      END IF;
    END IF;
  END PROCESS Latch_On_Active8_process;


  Unit_Delay_Enabled_Synchronous18_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_8 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_8 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_8 <= Cam_On_8_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous18_process;


  
  Relational_Operator38_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_8 = Unit_Delay_Enabled_Synchronous_out1_8 ELSE
      '0';

  
  switch_compare_1_53 <= '1' WHEN Relational_Operator38_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_17 <= Switch_out1_16 WHEN switch_compare_1_53 = '0' ELSE
      '0';

  
  FixPt_Relational_Operator36_relop1 <= '1' WHEN Direction /= Direction_1 ELSE
      '0';

  
  FixPt_Relational_Operator37_relop1 <= '1' WHEN Enable > Enable_1 ELSE
      '0';

  
  switch_compare_1_54 <= '1' WHEN FixPt_Relational_Operator36_relop1 > '0' ELSE
      '0';

  Bitwise_Operator3_out1_9 <=  NOT Direction;

  Cam_Off_9_unsigned <= unsigned(Cam_Off_9);

  
  switch_compare_1_55 <= '1' WHEN FixPt_Relational_Operator36_relop1 > '0' ELSE
      '0';

  Cam_On_9_unsigned <= unsigned(Cam_On_9);

  Bitwise_Operator_out1_27 <= Relational_Operator20_relop1 AND Relational_Operator110_relop1;

  
  Relational_Operator110_relop1 <= '1' WHEN Angle_unsigned >= Unit_Delay_Enabled_Synchronous1_out1_9 ELSE
      '0';

  
  Relational_Operator20_relop1 <= '1' WHEN Angle_unsigned <= Unit_Delay_Enabled_Synchronous_out1_9 ELSE
      '0';

  Bitwise_Operator1_out1_27 <= Relational_Operator20_relop1 OR Relational_Operator110_relop1;

  
  Relational_Operator29_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_9 > Unit_Delay_Enabled_Synchronous1_out1_9 ELSE
      '0';

  
  switch_compare_1_56 <= '1' WHEN Relational_Operator29_relop1 > '0' ELSE
      '0';

  
  Switch_out1_18 <= Bitwise_Operator1_out1_27 WHEN switch_compare_1_56 = '0' ELSE
      Bitwise_Operator_out1_27;

  Bitwise_Operator4_out1_9 <= FixPt_Relational_Operator38_relop1 AND Direction;

  Bitwise_Operator2_out1_9 <= FixPt_Relational_Operator39_relop1 AND Bitwise_Operator3_out1_9;

  Bitwise_Operator1_out1_28 <= Bitwise_Operator2_out1_9 OR Bitwise_Operator4_out1_9;

  
  Switch2_out1_9 <= Bitwise_Operator1_out1_28 WHEN switch_compare_1_55 = '0' ELSE
      Latch_Off_Active_out1_9;

  
  switch_compare_1_57 <= '1' WHEN Bitwise_Operator1_out1_29 > '0' ELSE
      '0';

  
  Switch_out1_19 <= Switch2_out1_9 WHEN switch_compare_1_57 = '0' ELSE
      '1';

  
  Compare_To_Zero1_out1_9 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_9 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator7_out1_9 <= FixPt_Relational_Operator39_relop1 AND Direction;

  Bitwise_Operator6_out1_9 <= FixPt_Relational_Operator38_relop1 AND Bitwise_Operator3_out1_9;

  Bitwise_Operator5_out1_9 <= Bitwise_Operator6_out1_9 OR Bitwise_Operator7_out1_9;

  
  Switch3_out1_9 <= Bitwise_Operator5_out1_9 WHEN switch_compare_1_54 = '0' ELSE
      Latch_On_Active_out1_9;

  
  switch_compare_1_58 <= '1' WHEN Bitwise_Operator1_out1_29 > '0' ELSE
      '0';

  
  Switch1_out1_18 <= Switch3_out1_9 WHEN switch_compare_1_58 = '0' ELSE
      '1';

  Latch_Off_Active9_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_Off_Active_out1_9 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_9 = '1' THEN
        Latch_Off_Active_out1_9 <= Switch1_out1_18;
      END IF;
    END IF;
  END PROCESS Latch_Off_Active9_process;


  Unit_Delay_Enabled_Synchronous10_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_9 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_Off_Active_out1_9 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1_9 <= Cam_Off_9_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous10_process;


  
  Compare_To_Zero_out1_9 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1_9 = to_unsigned(0, 32) ELSE
      '0';

  Bitwise_Operator_out1_28 <= Compare_To_Zero_out1_9 AND Compare_To_Zero1_out1_9;

  Bitwise_Operator1_out1_29 <= FixPt_Relational_Operator37_relop1 OR Bitwise_Operator_out1_28;

  
  FixPt_Relational_Operator38_relop1 <= '1' WHEN Switch1_out1_19 > Comparators_out1_9 ELSE
      '0';

  -- 
  -- Store in Global RAM
  -- 
  -- 
  -- Store in Global RAM
  reduced_11_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Comparators_out1_9 <= '0';
      ELSIF enb = '1' THEN
        Comparators_out1_9 <= Switch1_out1_19;
      END IF;
    END IF;
  END PROCESS reduced_11_process;


  
  FixPt_Relational_Operator39_relop1 <= '1' WHEN Switch1_out1_19 < Comparators_out1_9 ELSE
      '0';

  Bitwise_Operator_out1_29 <= FixPt_Relational_Operator39_relop1 OR FixPt_Relational_Operator38_relop1;

  Bitwise_Operator8_out1_9 <= Bitwise_Operator1_out1_29 OR (Bitwise_Operator_out1_29 OR FixPt_Relational_Operator36_relop1);

  Latch_On_Active9_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Latch_On_Active_out1_9 <= '0';
      ELSIF enb = '1' AND Bitwise_Operator8_out1_9 = '1' THEN
        Latch_On_Active_out1_9 <= Switch_out1_19;
      END IF;
    END IF;
  END PROCESS Latch_On_Active9_process;


  Unit_Delay_Enabled_Synchronous19_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_9 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND Latch_On_Active_out1_9 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1_9 <= Cam_On_9_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous19_process;


  
  Relational_Operator39_relop1 <= '1' WHEN Unit_Delay_Enabled_Synchronous1_out1_9 = Unit_Delay_Enabled_Synchronous_out1_9 ELSE
      '0';

  
  switch_compare_1_59 <= '1' WHEN Relational_Operator39_relop1 > '0' ELSE
      '0';

  
  Switch1_out1_19 <= Switch_out1_18 WHEN switch_compare_1_59 = '0' ELSE
      '0';

  Bitwise_Operator_out1_30 <= Switch1_out1_19 OR (Switch1_out1_17 OR (Switch1_out1_15 OR (Switch1_out1_13 OR (Switch1_out1_11 OR (Switch1_out1_9 OR (Switch1_out1_7 OR (Switch1_out1_5 OR (Switch1_out1_1 OR Switch1_out1_3))))))));

  Bitwise_Operator1_out1_30 <= Bitwise_Operator_out1_30 AND Enable;

  Bit_Slice_out1 <= to_unsigned(16#045#, 10);

  Bit_Concat_out1 <= "10" & (Bit_Slice_out1 & unsigned'("0000000011" & "0000000011"));

  Version <= std_logic_vector(Bit_Concat_out1);

  ce_out <= clk_enable;

  Camshaft <= Bitwise_Operator1_out1_30;

END rtl;

