-- -------------------------------------------------------------
-- 
-- File Name: tmp_vhdl\biss_sniffer_fpga_code_module\sg_bisssniffer_MATLAB_Function.vhd
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sg_bisssniffer_MATLAB_Function
-- Source Path: biss_sniffer_fpga_code_module/BISS Sniffer FPGA Code Module/Line Delay Compensation/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sg_bisssniffer_MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        MA                                :   IN    std_logic;
        lineDelay                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        y                                 :   OUT   std_logic
        );
END sg_bisssniffer_MATLAB_Function;


ARCHITECTURE rtl OF sg_bisssniffer_MATLAB_Function IS

  -- Signals
  SIGNAL lineDelay_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL MA_buf                           : std_logic_vector(0 TO 255);  -- boolean [256]
  SIGNAL MA_buf_next                      : std_logic_vector(0 TO 255);  -- boolean [256]

BEGIN
  lineDelay_unsigned <= unsigned(lineDelay);

  MATLAB_Function_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        MA_buf <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        MA_buf <= MA_buf_next;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_process;

  MATLAB_Function_output : PROCESS (MA, MA_buf, lineDelay_unsigned)
    VARIABLE MA_buf_temp : std_logic_vector(0 TO 255);
    VARIABLE add_temp : unsigned(8 DOWNTO 0);
    VARIABLE sub_cast : unsigned(7 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(31 DOWNTO 0);
  BEGIN
    MA_buf_temp := MA_buf;
    MA_buf_temp(1 TO 255) := MA_buf(0 TO 254);
    MA_buf_temp(0) := MA;
    add_temp := resize(lineDelay_unsigned, 9) + to_unsigned(16#001#, 9);
    IF add_temp(8) /= '0' THEN 
      sub_cast := "11111111";
    ELSE 
      sub_cast := add_temp(7 DOWNTO 0);
    END IF;
    sub_cast_0 := signed(resize(sub_cast, 32));
    y <= MA_buf_temp(to_integer(sub_cast_0 - 1));
    MA_buf_next <= MA_buf_temp;
  END PROCESS MATLAB_Function_output;


END rtl;

