-- -------------------------------------------------------------
-- 
-- File Name: tmp_vhdl\ssim_fpga_code_module\sg_ssim_SSI_Master_FPGA_Code_Module_pkg.vhd
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE sg_ssim_SSI_Master_FPGA_Code_Module_pkg IS
  TYPE T_ChartModeType IS (None, x_IDLE, sTX_START, sSCK_1st_low, sSCK_1st_high, sSCK_HIGH, sTP, sTL_LOW, sTL, sSCK_SYMM, sSCK_LOW, sNEXT_BIT);
  TYPE T_state_type_is_Chart IS (IN_sNEXT_BIT, IN_sSCK_1st_high, IN_sSCK_1st_low, IN_sSCK_HIGH, IN_sSCK_LOW, IN_sSCK_SYMM, IN_sTL, IN_sTL_LOW, IN_sTP, IN_sTX_START, IN_x_IDLE);
END sg_ssim_SSI_Master_FPGA_Code_Module_pkg;

