-- -------------------------------------------------------------
-- 
-- File Name: tmp_vhdl\ssis_fpga_code_module\sg_ssis_SSI_Slave_FPGA_Code_Module_pkg.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE sg_ssis_SSI_Slave_FPGA_Code_Module_pkg IS
  TYPE T_ControlModeType IS (None, xIDLE, sTRANSFER, sTRANSFER_TIMEOUT, sCLR_CLKTMO);
  TYPE T_state_type_is_Control IS (IN_sCLR_CLKTMO, IN_sTRANSFER, IN_sTRANSFER_TIMEOUT, IN_xIDLE);
END sg_ssis_SSI_Slave_FPGA_Code_Module_pkg;

